name: tuna
on: push
jobs:
 nuget:
   name: release nuget
   runs-on: windows-latest
   steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-dotnet@v1
  

