name: tuna
on: 
 push: 
  branches: 
   - main 


jobs:
 nuget:
   strategy: 
    matrix: 
     version: [Rvt_16_Release, Rvt_17_Release, Rvt_18_Release, Rvt_19_Release, Rvt_20_Release, Rvt_21_Release, Rvt_22_Release, Rvt_23_Release, Rvt_24_Release]
   name: release nuget
   runs-on: windows-latest
   steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3.2.0
      with:
    # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
       dotnet-version: 6.0.2xx
       
    - name: checkout
      uses: actions/checkout@v4.0.0
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration ${{ matrix.version }}
      
    - name: Publish NuGet
      run: dotnet nuget push src\bin\${{ matrix.version }}\*.nupkg -k ${{secrets.NUGETKEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate

