name: tuna
on: 
 push: 
  branches: 
   - main 
jobs:
 nuget:
   name: release nuget
   runs-on: windows-latest
   steps:
    - name: checkout
      uses: actions/checkout@v4.0.0

    - name: Build DotNet
      uses: Elskom/build-dotnet@v1.1.1
      
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with: 
       PROJECT_FILE_PATH: src/Tuna.Revit.Extension.csproj
       BUILD_CONFIGURATION: Rvt_20_Release
       NUGET_KEY: ${{secrets.NUGETKEY}}
       NUGET_SOURCE: https://api.nuget.org

