name: tuna
on: 
 push: 
  branches: 
   - main 


jobs:
 nuget:
   name: release nuget
   runs-on: windows-latest
   steps:
    - name: checkout
    - uses: actions/checkout@v4.0.0
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Rvt_16_Release
        
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with: 
       PROJECT_FILE_PATH: src/Tuna.Revit.Extension.csproj
       BUILD_CONFIGURATION: Rvt_16_Release
       NUGET_KEY: ${{secrets.NUGETKEY}}
       NUGET_SOURCE: https://api.nuget.org/v3/index.json

