name: tuna
on: 
 push: 
  branches: 
   - main 


jobs:
 nuget:
   name: release nuget
   runs-on: windows-latest
   steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Rvt_16_Release

    - name: path
      run: cd src\bin\Rvt_16_Release

    - name: paths
      run: cd..
      
    - name: show
      run: dir
      
    - name: Publish NuGet
      run: dotnet nuget push src\bin\Rvt_16\Release\Tuna.Revit.Extension.2016.2.8.nupkg -k ${{secrets.NUGETKEY}} -s https://api.nuget.org/v3/index.json

