name: tuna
on: 
 push: 
  branches: 
   - main 


jobs:
 nuget:
   name: release nuget
   runs-on: windows-latest
   steps:
    - name: checkout
      uses: actions/checkout@v4.0.0
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Rvt_16_Release

    - name: bin
      run: cd bin
      
    - name: release
      run: Rvt_16_Release
        
    - name: Publish NuGet
      run: dotnet nuget push *.nupkg -k ${{secrets.NUGETKEY}} -s https://api.nuget.org/v3/index.json

