name: tuna
on: push
jobs:
 nuget:
   name: release nuget
   runs-on: windows-2022
   steps:
    - name: checkout
      uses: actions/checkout@v2
  
    - name: puiblish
      run: ./.nuke/build.cmd --GitHUbToken ${{ secrets.NUGETKEY }}
   
