name: tuna
on: 
 push: 
  branches: 
   - main 

env:
  DOTNET_VERSION: '4.7.x'
jobs:
 nuget:
   name: release nuget
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v4.0.0
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore


      
    - name: Build
      run: dotnet build --configuration Rvt_20_Release --no-restore
        
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with: 
       PROJECT_FILE_PATH: src/Tuna.Revit.Extension.csproj
       BUILD_CONFIGURATION: Rvt_16_Release
       NUGET_KEY: ${{secrets.NUGETKEY}}
       NUGET_SOURCE: https://api.nuget.org

